Repository VictorVasconcellos42/Minecasting, pull requests merged in 2023-07, with the labels that each got.

#25 Feature/movement
  include/cub3d.h
  include/raycasting.h
  maps/lay1.cub
  maps/lay2.cub
  maps/lay3.cub
  maps/lay4.cub
  maps/lay5.cub
  sources/integration/hooks.c
  sources/integration/integration.c
  sources/integration/moviment.c
  sources/raycasting/engine_utils.c
  sources/raycasting/init.c
  sources/raycasting/load_engine.c
  sources/raycasting/main.c
Labels: bug

#26 Hotfix/horizontal moviment
  include/cub3d.h
  sources/integration/hooks.c
  sources/integration/moviment.c
  sources/raycasting/init.c
Labels: bug

#28 feat: colision create more or less but ok
  sources/integration/moviment.c
Labels: enhancement

#29 Fix/vision-start-dir
  include/raycasting.h
  sources/integration/integration.c
  sources/integration/vision.c
Labels: bug, enhancement

#31 Norma: Normalizing and compiling fixed
  include/cub3d.h
  sources/model/scene_reading/texture_init.c
  sources/raycasting/engine_utils.c
  sources/raycasting/load_engine.c
  sources/raycasting/paint.c
Labels: bug
