Repository VictorVasconcellos42/Minecasting, pull requests merged in 2023-05, with the labels that each got.

#1 Feature/scene reading
  docs/Scene_Reading.md
  include/cub3d.h
  include/parse.h
  library/libft/get_next_line.h
  maps/map.cub
  sources/main.c
  sources/model/input_reading/input_reading.c
  sources/model/map_reading/.map_reading.c.swp
  sources/model/map_reading/colors_reading.c
  sources/model/map_reading/map_reading.c
  sources/model/map_reading/map_utils.c
  sources/model/map_reading/matrix_utils.c
  sources/model/map_reading/resolution_sprite_reading.c
  sources/model/map_reading/texture_reading.c
  sources/model/map_reading/texture_utils.c
  sources/tests/config.c.backup
  sources/tests/reading_test.c
  sources/tests/teste
Labels: documentation, enhancement

#4 Norminette: Putting in norm standard
  include/cub3d.h
  sources/raycasting/paint.c
Labels: bug

#8 Estruturação da CUB3D - FASE INICIAL
  include/cub3d.h
  include/parse.h
  sources/model/map_reading/map_reading.c
  sources/model/map_reading/matrix_utils.c
  sources/raycasting/main.c
  sources/raycasting/paint.c
  tests/paint_line_in_window.c
Labels: enhancement, help wanted

#10 Documentation/systems
  .gitignore
  README.md
  docs/README.md
  docs/systems/Actions.md
  docs/systems/GarbageCollector.md
Labels: documentation

#12 Feature/raycasting engine untextured
  include/cub3d.h
  include/raycasting.h
  maps/map.cub
  sources/model/scene_reading/matrix_utils.c
  sources/model/scene_reading/scene_reading.c
  sources/raycasting/engine_utils.c
  sources/raycasting/init.c
  sources/raycasting/load_engine.c
  sources/raycasting/main.c
  sources/raycasting/paint.c
Labels: enhancement, help wanted
